- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: pull docker image
      shell: /opt/homebrew/bin/docker pull vismayasolanki/spe_mini_project_calc

    - name: running container
      shell: /opt/homebrew/bin/docker run -it -d -p 6000:6000 vismayasolanki/spe_mini_project_calc




